# Generated by Django 4.2.3 on 2024-01-08 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.TextField(primary_key=True, serialize=False)),
                ('features', models.TextField()),
                ('propertyimage_link', models.TextField()),
                ('addressline1', models.TextField()),
                ('pincode', models.IntegerField()),
                ('created_at', models.DateField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.TextField(primary_key=True, serialize=False)),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('created_at', models.DateField()),
                ('password', models.CharField(max_length=20, null=True)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_size', models.IntegerField()),
                ('created_at', models.DateField()),
                ('unit_bhk_size', models.TextField()),
                ('rent_value', models.IntegerField()),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.property')),
            ],
        ),
        migrations.CreateModel(
            name='TenentRentAggriment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_value', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tenent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usertable')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.units')),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='property_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usertable'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.TextField()),
                ('document_path', models.TextField()),
                ('isverified', models.BooleanField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertable')),
            ],
        ),
    ]
